export const GET_TASK_PENDING = "GET_TASK_PENDING";
export const GET_TASK_SUCCESSFUL = "GET_TASK_SUCCESSFUL";
export const GET_TASK_FAILED = "GET_TASK_FAILED";


export const GET_MY_TASK = "GET_MY_TASK";
export const GET_SINGLE="GET_SINGLE";
