export const LOGIN_SUCCESSFUL="LOGIN_SUCCESSFUL";
export const LOGIN_FAILED="LOGIN_FAILED";
export const LOGIN_PENDING="LOGIN_PENDING";

export const REGISTER_PENDING="REGISTER_PENDING";
export const REGISTER_SUCCESSFUL="REGISTER_SUCCESSFUL";
export const REGISTER_FAILED="REGISTER_FAILED";

export const LOG_OUT="LOG_OUT";